/**
 * @module core/dom-refs
 *
 * @description
 * Centralne pobieranie referencji do elementów DOM aplikacji QuickEvo.
 * Ułatwia to refaktoryzację entrypointu, testowanie (mockowanie DOM) oraz ogranicza
 * liczbę rozproszonych odwołań do document.getElementById.
 */

/**
 * Zwraca zestaw referencji do kluczowych elementów DOM.
 *
 * Uwaga:
 * - Wartości mogą być `null`, jeśli element nie istnieje w aktualnym wariancie UI.
 * - Obiekt jest zamrożony, aby ograniczyć przypadkowe nadpisania referencji.
 *
 * @returns {Readonly<{
 *   searchInput: HTMLInputElement|null,
 *   resultsList: HTMLElement|null,
 *   resultsInfo: HTMLElement|null,
 *   statusIndicator: HTMLElement|null,
 *   fileCountSpan: HTMLElement|null,
 *   searchSortToggle: HTMLElement|null,
 *   themeToggle: HTMLElement|null,
 *   themeIcon: HTMLElement|null,
 *   googleDriveButton: HTMLElement|null,
 *   scheduleButton: HTMLElement|null,
 *   navRoutesButton: HTMLElement|null,
 *   navDriversButton: HTMLElement|null,
 *   navScheduleButton: HTMLElement|null,
 *   uploadProgressContainer: HTMLElement|null,
 *   uploadProgress: HTMLProgressElement|null,
 *   uploadStatus: HTMLElement|null,
 *   searchView: HTMLElement|null,
 *   routesView: HTMLElement|null,
 *   routesStandardGrid: HTMLElement|null,
 *   routesEveningGrid: HTMLElement|null,
 *   routesWeekendGrid: HTMLElement|null,
 *   driversView: HTMLElement|null,
 *   driversGrid: HTMLElement|null,
 *   filePreviewView: HTMLElement|null,
 *   backToSearchBtn: HTMLButtonElement|null,
 *   scheduleView: HTMLElement|null,
 *   backToSearchFromScheduleBtn: HTMLButtonElement|null,
 *   scheduleTableHeader: HTMLElement|null,
 *   scheduleTableBody: HTMLElement|null,
 *   scheduleMonthSelect: HTMLSelectElement|null,
 *   schedulePrevMonthBtn: HTMLButtonElement|null,
 *   scheduleNextMonthBtn: HTMLButtonElement|null,
 *   scheduleTodayBtn: HTMLButtonElement|null,
 *   scheduleSubtitle: HTMLElement|null,
 *   previewMeta: HTMLElement|null,
 *   loadingOverlay: HTMLElement|null,
 *   loadingTitleText: HTMLElement|null,
 *   loadingStatusText: HTMLElement|null,
 *   loadingProgressBar: HTMLProgressElement|null,
 *   loadingProgressMeta: HTMLElement|null,
 *   loadingError: HTMLElement|null,
 *   loadingContinueButton: HTMLButtonElement|null,
 *   appShell: HTMLElement|null,
 *   appHeaderLogo: HTMLElement|null,
 *   homeLink: HTMLAnchorElement|null,
 *   syncGDriveButton: HTMLButtonElement|null,
 *   modalOverlay: HTMLElement|null,
 *   modalTitle: HTMLElement|null,
 *   modalContent: HTMLElement|null,
 *   modalActions: HTMLElement|null,
 *   welcomeImportProgress: HTMLElement|null,
 *   welcomeProgressList: HTMLElement|null,
 *   ghostOverlay: HTMLElement|null,
 *   ghostPrefix: HTMLElement|null,
 *   ghostSuffix: HTMLElement|null,
 *   ghostHint: HTMLButtonElement|null,
 *   previewFileName: HTMLElement|null,
 *   previewTableHeader: HTMLElement|null,
 *   previewTableBody: HTMLElement|null,
 *   welcomeGraphic: HTMLElement|null
 * }>}
 */
export function getAppDomRefs() {
    return Object.freeze({
        searchInput: document.getElementById('search-input'),
        resultsList: document.getElementById('results-list'),
        resultsInfo: document.getElementById('results-info'),
        statusIndicator: document.getElementById('status-indicator'),
        fileCountSpan: document.getElementById('file-count'),
        searchSortToggle: document.getElementById('search-sort-toggle'),
        themeToggle: document.getElementById('theme-toggle'),
        themeIcon: document.getElementById('theme-icon'),
        googleDriveButton: document.getElementById('import-google-drive-button'),
        scheduleButton: document.getElementById('schedule-button'),
        navRoutesButton: document.getElementById('nav-routes-button'),
        navDriversButton: document.getElementById('nav-drivers-button'),
        navScheduleButton: document.getElementById('nav-schedule-button'),
        uploadProgressContainer: document.getElementById('upload-progress-container'),
        uploadProgress: document.getElementById('upload-progress'),
        uploadStatus: document.getElementById('upload-status'),
        searchView: document.getElementById('search-view'),
        routesView: document.getElementById('routes-view'),
        routesStandardGrid: document.getElementById('routes-standard-grid'),
        routesEveningGrid: document.getElementById('routes-evening-grid'),
        routesWeekendGrid: document.getElementById('routes-weekend-grid'),
        driversView: document.getElementById('drivers-view'),
        driversGrid: document.getElementById('drivers-grid'),
        filePreviewView: document.getElementById('file-preview-view'),
        backToSearchBtn: document.getElementById('back-to-search'),
        scheduleView: document.getElementById('schedule-view'),
        backToSearchFromScheduleBtn: document.getElementById('back-to-search-from-schedule'),
        scheduleTableContainer: document.getElementById('schedule-table-container'),
        scheduleTableHeader: document.getElementById('schedule-table-header'),
        scheduleTableBody: document.getElementById('schedule-table-body'),
        scheduleMonthSelect: document.getElementById('schedule-month-select'),
        scheduleMonthTrigger: document.getElementById('schedule-month-trigger'),
        scheduleMonthTriggerLabel: document.getElementById('schedule-month-trigger-label'),
        scheduleMonthToggle: document.getElementById('schedule-month-toggle'),
        scheduleMonthOptions: document.getElementById('schedule-month-options'),
        schedulePrevMonthBtn: document.getElementById('schedule-prev-month'),
        scheduleNextMonthBtn: document.getElementById('schedule-next-month'),
        scheduleTodayBtn: document.getElementById('schedule-today'),
        scheduleSelectedDay: document.getElementById('schedule-selected-day'),
        scheduleSubtitle: document.getElementById('schedule-subtitle'),
        scheduleDriverFilter: document.getElementById('schedule-driver-filter'),
        scheduleDriverFilterToggle: document.getElementById('schedule-driver-filter-toggle'),
        scheduleDriverFilterOptions: document.getElementById('schedule-driver-filter-options'),
        scheduleRouteFilter: document.getElementById('schedule-route-filter'),
        scheduleRouteFilterToggle: document.getElementById('schedule-route-filter-toggle'),
        scheduleRouteFilterOptions: document.getElementById('schedule-route-filter-options'),
        scheduleClearFiltersBtn: document.getElementById('schedule-clear-filters'),
        previewMeta: document.getElementById('preview-meta'),
        loadingOverlay: document.getElementById('loading-overlay'),
        loadingTitleText: document.getElementById('welcome-text'),
        loadingStatusText: document.getElementById('loading-status-text'),
        loadingProgressBar: document.getElementById('loading-progress-bar'),
        loadingProgressMeta: document.getElementById('loading-progress-meta'),
        loadingError: document.getElementById('loading-error'),
        loadingContinueButton: document.getElementById('loading-continue-button'),
        appShell: document.getElementById('app-shell'),
        appHeaderLogo: document.getElementById('app-header-logo'),
        homeLink: document.getElementById('home-link'),
        syncGDriveButton: document.getElementById('sync-gdrive-button'),
        modalOverlay: document.getElementById('modal-overlay'),
        modalTitle: document.getElementById('modal-title'),
        modalContent: document.getElementById('modal-content'),
        modalActions: document.getElementById('modal-actions'),
        welcomeImportProgress: document.getElementById('welcome-import-progress'),
        welcomeProgressList: document.getElementById('welcome-progress-list'),
        ghostOverlay: document.getElementById('qe-ghost'),
        ghostPrefix: document.getElementById('qe-ghost-prefix'),
        ghostSuffix: document.getElementById('qe-ghost-suffix'),
        ghostHint: document.getElementById('qe-ghost-hint'),
        previewFileName: document.getElementById('preview-filename'),
        previewTableHeader: document.getElementById('table-header'),
        previewTableBody: document.getElementById('table-body'),
        welcomeGraphic: document.getElementById('welcome-graphic')
    });
}

